In [1]:
import numpy as np

In [16]:
arr=np.array([2,3,2,4])

In [19]:
arr[0]=5
print(arr)

[5 3 2 4]


In [20]:
print(type(arr))

<class 'numpy.ndarray'>


In [21]:
print("shape of the array",arr.shape)

shape of the array (4,)


In [28]:
arrn=np.array(
    [
        [
            [2,3,2,1],
            [3,43,2,4],
            [89,32,23,43],
        ],
        [
            [2,3,2,1],
            [3,43,2,4],
            [89,32,23,43],
        ],
        [
            [2,3,2,1],
            [3,43,2,4],
            [89,32,23,43]
        ]
    ]
)

C:\Users\subhajit\AppData\Local\Temp\ipykernel_3160\3195367090.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arrn=np.array(


In [29]:
print(arrn)

[[[2 3 2 1]
  [3 43 2 4]
  [89 32 23 43]
  [list([2, 3, 2, 1]) list([3, 43, 2, 4]) list([89, 32, 23, 43])
   list([[2, 3, 2, 1], [3, 43, 2, 4], [89, 32, 23, 43]])]]]
